### ISSUE TITLE
instance status

### ISSUE THREAD

**Issue by nibblehole** [searx/searx-stats2#60]
is the website - https://searx.space/ still checking the instance status? it looks like the process to check the condition of instances stopped a few days ago.

**Comment by unixfox** [comment]
Could you explain why you think it's the case?

**Comment by nibblehole** [comment]
because one of the instances has changed location but you can still see the old one and the search response time has not changed for all instances in a few days

**Comment by unixfox** [comment]
Why instance? Could you be a bit more descriptive?

**Comment by nibblehole** [comment]
location changed two days ago https://nibblehole.com/ new location DE + IPv6 and CSP  A+
Search response time for the other instances it is still the same - I made the screenshots ;)

**Comment by dalf** [comment]
I can confirm the issue.

https://searx.space/data/instances.json

`metadata.timestamp` is 1608501686 , 5 days ago.

**Comment by dalf** [comment]
Call stack:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/searxstats/searxstats/__main__.py", line 116, in <module>
    main()
  File "/usr/local/searxstats/searxstats/__main__.py", line 112, in main
    list(update_fetcher_memoize_list))
  File "/usr/local/searxstats/searxstats/__main__.py", line 46, in run
    loop.run_until_complete(run_function(output_file_name, private, instance_urls, selected_fetcher_names))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/searxstats/searxstats/__init__.py", line 47, in run_once
    await fetch(searx_stats_result, selected_fetchers)
  File "/usr/local/searxstats/searxstats/fetcher/__init__.py", line 70, in fetch
    await wait_get_results(*tasks_for_group)
  File "/usr/local/searxstats/searxstats/common/utils.py", line 86, in wait_get_results
    raise exception
  File "/usr/local/searxstats/searxstats/common/utils.py", line 80, in wait_get_results
    results.append(task.result())
  File "/usr/local/searxstats/searxstats/fetcher/network.py", line 283, in fetch
    await _fetch_network(searx_stats_result)
  File "/usr/local/searxstats/searxstats/fetcher/network.py", line 229, in _fetch_network
    fetch_one, searx_stats_result)
  File "/usr/local/searxstats/searxstats/common/foreach.py", line 131, in for_each
    await loop.run_in_executor(executor, _for_each_in_thread, iterator, function, *args)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/searxstats/searxstats/common/foreach.py", line 14, in _for_each_in_thread
    function(*args, *item)
  File "/usr/local/searxstats/searxstats/fetcher/network.py", line 222, in fetch_one
    network_detail = get_network_info(searx_stats_result, instance_host)
  File "/usr/local/searxstats/searxstats/fetcher/network.py", line 209, in get_network_info
    result['ips'][address] = get_address_info(searx_stats_result, address, field_type, True)
  File "/usr/local/searxstats/searxstats/fetcher/network.py", line 151, in get_address_info
    whois_info, whois_info_error = get_whois(address)
  File "/usr/local/searxstats/searxstats/common/memoize.py", line 174, in wrapped_f
    result = func(*args, **kwargs)
  File "/usr/local/searxstats/searxstats/fetcher/network.py", line 119, in get_whois
    obj = ipwhois.IPWhois(address)
  File "/usr/local/lib/python3.7/site-packages/ipwhois/ipwhois.py", line 55, in __init__
    allow_permutations=allow_permutations
  File "/usr/local/lib/python3.7/site-packages/ipwhois/net.py", line 193, in __init__
    self.address_str, is_defined[1], is_defined[2]
ipwhois.exceptions.IPDefinedError: IPv6 address [redacted] is already defined as Link-Local via RFC 4291, Section 2.5.6.
```

**Comment by dalf** [comment]
searx.space is up to date.
updates won't break on the same error.

**Comment by canbeup** [comment]
I think that the same problem has occurred
