### ISSUE TITLE
instance status - I think that the same problem has occurred

### ISSUE THREAD

**Issue by canbeup** [searx/searx-stats2#64]
I think that the same problem has occurred

_Originally posted by @canbeup in https://github.com/searx/searx-stats2/issues/60#issuecomment-757471333_

**Comment by unixfox** [comment]
Could you tell us the name of the affected instance?

**Comment by canbeup** [comment]
for two days the instance https://searx.prvcy.eu/ has Search response time: 0.284 which is unrealistic for the result to be linear

**Comment by dalf** [comment]
Different error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/searxstats/searxstats/__main__.py", line 116, in <module>
    main()
  File "/usr/local/searxstats/searxstats/__main__.py", line 112, in main
    list(update_fetcher_memoize_list))
  File "/usr/local/searxstats/searxstats/__main__.py", line 46, in run
    loop.run_until_complete(run_function(output_file_name, private, instance_urls, selected_fetcher_names))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/searxstats/searxstats/__init__.py", line 47, in run_once
    await fetch(searx_stats_result, selected_fetchers)
  File "/usr/local/searxstats/searxstats/fetcher/__init__.py", line 70, in fetch
    await wait_get_results(*tasks_for_group)
  File "/usr/local/searxstats/searxstats/common/utils.py", line 86, in wait_get_results
    raise exception
  File "/usr/local/searxstats/searxstats/common/utils.py", line 80, in wait_get_results
    results.append(task.result())
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/searxstats/searxstats/fetcher/external_ressources.py", line 280, in fetch
    fetch_instances(searx_stats_result, network_type, ressource_hashes)
  File "/usr/local/searxstats/searxstats/fetcher/external_ressources.py", line 250, in fetch_instances
    driver = new_driver(network_type=network_type)
  File "/usr/local/searxstats/searxstats/fetcher/external_ressources.py", line 62, in new_driver
    service_args=['--log', 'info'])
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
```

**Comment by canbeup** [comment]
I'm not saying that the same problem happened from the server side, but for the end user the problem is the same - incorrect instance status.

**Comment by dalf** [comment]
The issue is fixed https://searx.space has been updated.

Technically:
   * searx-stats2 won't break anymore because one metric (aka fetcher) is broken: commit https://github.com/searx/searx-stats2/commit/3250fff3b1802bd2588785833502d47e11568692
   * searx-stats2 use [firefox-esr](https://packages.debian.org/buster/firefox-esr) instead of the last version to fix the HTML grade error: commit https://github.com/searx/searx-stats2/commit/58d0370a3304cda672fa322e6fb1e5d9a1ee8e50

Nice to have:
* from the user point of view, `timestamp` from `https://searx.space/data/instances.json` should be displayed clearly. To be done with https://github.com/searx/searx-stats2/pull/25
* an alert could be sent if this `timestamp` is not updated for 6 hours.
